added(application header)
ramilqO/road-rules pull request #2
Opened 2024-08-11 20:37 UTC by Twaiz

Added "header" in web-site

2024-08-11 20:43 UTC, GitStudentSem commented on public/svg/cap/Moon01.tsx
Лучше переменовать файл в MoonIcon что бы было ясно что это именно иконка, а не просто компонент

2024-08-11 20:43 UTC, GitStudentSem commented on public/svg/cap/Sun01.tsx
Лучше переменовать файл в SunIcon что бы было ясно что это именно иконка, а не просто компонент

2024-08-11 20:44 UTC, GitStudentSem commented on public/svg/iconProject/check-list-icon.svg
Не понятно что это за иконка, ее нет в макете

2024-08-11 20:45 UTC, GitStudentSem commented on src/styleComponents/Cap.module.scss
> +  height: 48px;
Кнопка 44 на 44 по макету

2024-08-11 20:46 UTC, GitStudentSem commented on src/styleComponents/Cap.module.scss
Пока что пусть будет так, чуть позже я вынесу все цвета на макете в отдельную палитру и их нужно будет использовать как css переменные

2024-08-11 20:49 UTC, GitStudentSem commented on index.html
>  <html lang="en">
Язык можно выставить ru так как весь сайт на русском

2024-08-11 20:49 UTC, GitStudentSem commented on index.html
> +    <title>Road Rules</title>
Заголовок можно написать как Тестирование | ПДД сайт на Русском и заголовок так же можно сделать русским

2024-08-11 20:52 UTC, GitStudentSem requested changes
Нужно поправить места которые я описал в реквесте

2024-08-11 21:05 UTC, ramilqO requested changes

2024-08-11 21:05 UTC, ramilqO commented on src/ui/Cap.tsx
> +export default function Cap() {
Переименуй компонент на Header. Я понимаю, что технически Cap это верно, но так никто не поймёт:)

2024-08-11 21:05 UTC, ramilqO commented on src/ui/Cap.tsx
Удали папку styleComponents и храни файл со стилями около самого компонента в одной папке, это хорошая практика.
Например:
Папка Header --> Header.tsx, Header.module.scss
Также перенеси этот компонент в папку components, к ui компонентам относятся компоненты с минимальным количеством логики: Button, Input и.т.п.
Пока что в целом можно все компоненты скидывать в папку components, а папку ui удалить.

2024-08-11 21:05 UTC, ramilqO commented on src/ui/Cap.tsx
> +              className={`${style.navigation__authItemButton} ${style["navigation__authItemButton--login"]}`} // когда пользователь авторизован будет добавлятся вот этот класс --- ${style["navigation
Очень большой класс. Сделай в компоненте одну переменную isAuth и тернарным оператором рендери то, что тебе нужно.

2024-08-11 21:05 UTC, ramilqO commented on src/styleComponents/Cap.module.scss
> +.navigation {
Пустой класс. Удали.

2024-08-11 21:05 UTC, ramilqO commented on src/styleComponents/Cap.module.scss
> +.navigation__authItem {
Снова пустой класс

2024-08-11 21:05 UTC, ramilqO commented on src/styleComponents/Cap.module.scss
Стоит вынести scss переменные цветов в отдельный файл variables.scss и использовать в других компонентах.

2024-08-11 21:05 UTC, ramilqO commented on src/styleComponents/Cap.module.scss
А я как раз по поводу этого написал:)

2024-08-11 21:05 UTC, ramilqO commented on public/svg/cap/Sun01.tsx
Так может просто закинуть все svg в отдельную папку и импортить оттуда, а не создавать компонент?

2024-08-11 21:17 UTC, GitStudentSem commented on src/ui/Cap.tsx
> +              className={`${style.navigation__authItemButton} ${style["navigation__authItemButton--login"]}`} // когда пользователь авторизован будет добавлятся вот этот класс --- ${style["navigation
Так и должно быть, по макеты там 2 кнопки сразу и стоят

2024-08-11 21:29 UTC, GitStudentSem commented on public/svg/cap/Sun01.tsx
Они должны быть в виде TSX файлов иначе он не сможет создавать темы для них если они будут в img

2024-08-11 21:39 UTC, ramilqO requested changes

2024-08-11 21:39 UTC, ramilqO commented on src/styleComponents/Cap.module.scss
> +.cap__buttonChangeTheme {
Используй возможности scss.
Ты мог написать стили для buttonChangeTheme внутри блока со стилями cap.
.cap {
    &__buttonChangeTheme {}
}

2024-08-12 07:03 UTC, Twaiz commented on public/svg/iconProject/check-list-icon.svg
Её нет в макете. Я просто поставил ради красоты, чтобы не весел значок серый

2024-08-12 07:11 UTC, Twaiz commented on src/styleComponents/Cap.module.scss
я это и хотел сделать, но я в замешательстве какие у нас есть все цвета

2024-08-12 07:11 UTC, Twaiz commented on src/styleComponents/Cap.module.scss
> +.navigation {
оно автоматом у меня добавилось через расширение

2024-08-12 07:11 UTC, Twaiz commented on src/styleComponents/Cap.module.scss
> +.navigation__authItem {
оно автоматом у меня добавилось через расширение

2024-08-12 07:12 UTC, Twaiz commented on src/styleComponents/Cap.module.scss
> +.cap__buttonChangeTheme {
я пытаюсь использовать вложенности когда это и вправду надо, а в этом моменте, оно только усложняет читабельность

2024-08-12 07:16 UTC, Twaiz commented on src/styleComponents/Cap.module.scss
> +.cap__buttonChangeTheme {
Забираю свои слова обратно!

2024-08-12 07:23 UTC, merged